redux store provider setup
habitoz/awesome-book-react pull request #3
Opened 2023-07-27 15:03 UTC by habitoz

in this commit  i have updated the following files.
 * BookForm.jsx updated to handle add book functionality
 * BookCard.jsx updated to add remove button and its functionality.

2023-07-27 15:44 UTC, Ibizugbe requested changes
Hi @habitoz 👋🏼👋🏼👋🏼👋🏼, 

![require_changes](https://github.com/habitoz/awesome-book-react/assets/64643995/e2f07be7-6f6b-40f3-b8d3-b135ac6bdeed)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Linters are passing👍🏼.
- [x] it is possible to add a book👍🏼.
- [x]  The main React component is wrapped with the <Provider> component from react-redux👍🏼.
- [x] The Redux `store` has been passed into the `<Provider>`


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 15:44 UTC, Ibizugbe commented on src/Forms/book-form/BookForm.jsx
> +/* eslint-disable jsx-a11y/anchor-is-valid, react/jsx-curly-brace-presence, react/prop-types */
Kindly take away every line of code that disables `eslint` in your application😉. we are required to make use of linters to ensure we write code void of bad practices😉. Kindly do well to fix all your linter errors👍🏼.

2023-07-27 15:44 UTC, Ibizugbe commented on src/Forms/book-form/BookForm.jsx
> +          <option value="catagory 4">Cat 4</option>
Nice job so far👍🏼. currently, it is impossible to remove a book and I think it is because there is no actual function created to remove books. I think you only attached a function to the event handler of the remove button but the function wasn't created. That is just a suggestion tho. but kindly ensure it is possible to remove a book😉.

Also, let's add an input field for the name of the book so that when a book is created, we get to see the name of the book and the author😉.  as this is what is required in this milestone.

<img width="743" alt="image" src="https://github.com/habitoz/awesome-book-react/assets/64643995/bc6ea7e9-1620-4c58-84ed-399057d323cc">


https://github.com/habitoz/awesome-book-react/assets/64643995/884875e1-d07e-4a08-b9db-3ebbf52d13c0

2023-07-29 09:21 UTC, V-Blaze requested changes
## Hi @habitoz , 

# Almost there 🟡 

![giphy](https://user-images.githubusercontent.com/107632780/228988839-8679641a-a056-4909-a594-bcecacef173b.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, and some changes from the previous reviewers, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Correct Git flow✔
- Readme looks professional :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-29 09:21 UTC, V-Blaze commented on src/components/BookCard.jsx
> +}) {
- [ ] You have done great so far, but there are still some requirements you are yet to implement, 
- [ ] As pointed out by the previous about your remove button, I can see you added a `Remove book` button at the end of every book card. looking at the UI you can see there is already a `remove` in the design, that's where you are meant to add the functionality to remove a book, you are not meant to create a new button for that. :+1: :+1: 

- - Screenshot:
![Selection_001](https://github.com/habitoz/awesome-book-react/assets/107632780/9e0132e3-1b3c-4872-98a0-52e2232bc9a5)
- - Code Screenshot:
![Selection_002](https://github.com/habitoz/awesome-book-react/assets/107632780/a2d87141-6338-4bba-b6cc-3c4efe96bd50)

- [ ] As I pointed out above, that's where you are meant to add the functionality to remove a book. :+1: :+1: Hope that's clear enough :+1:

2023-07-29 09:21 UTC, V-Blaze commented on src/Forms/book-form/BookForm.jsx
> +          <option value="catagory 1">Cat 1</option>
- [ ] As pointed out by the previous reviewer, your add book form is missing the `Author field`. Your Add book form is meant to have 4 inputs, `Title, Author, and Category`. I'll suggest you add the Author's input to the form. :+1: :smile: 

- - Screenshot of the required inputs:
![Screenshot from 2023-07-29 10-01-02](https://github.com/habitoz/awesome-book-react/assets/107632780/ba5b9ff2-5a5c-4d5f-b35f-f2b417c13d44)

2023-07-29 09:21 UTC, V-Blaze commented on src/pages/books/Books.jsx
>  /*  eslint-disable react/jsx-curly-brace-presence, no-unused-vars */
- [ ] As required by Microverse you are not meant to use any linter `disable rule` in your codebase, the linters are there to make sure your code follows the best practices. I'll suggest you remove the linters disable rule and fix the errors. :+1: :100:

2023-07-29 09:21 UTC, V-Blaze commented on src/components/BookCard.jsx
>  /* eslint-disable jsx-a11y/anchor-is-valid, react/prop-types,react/jsx-curly-brace-presence */
- [ ] As pointed out above, As required by Microverse you are not meant to use any linter `disable rule` in your codebase, the linters are there to make sure your code follows the best practices. I'll suggest you remove the linters disable rule and fix the errors. :+1: :100:

2023-07-29 09:21 UTC, V-Blaze commented on src/Forms/book-form/BookForm.jsx
> +/* eslint-disable jsx-a11y/anchor-is-valid, react/jsx-curly-brace-presence, react/prop-types */
- [ ] As pointed out above, As required by Microverse you are not meant to use any linter `disable rule` in your codebase, the linters are there to make sure your code follows the best practices. I'll suggest you remove the linters disable rule and fix the errors. :+1: :100: 

## I'll suggest you go through your code and remove all the linters diable rule in every component too. the ones in the `Header, Footer` component and the `index.js` file :+1: :wave:

2023-07-29 09:42 UTC, sumairq reviewed
Hi @habitoz , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the linters passing.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-29 10:07 UTC, AshakaE approved these changes
Hi @habitoz   , 

### Highlights ✨ 

- Thanks for making the requested changes 👍 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Proceed to the next level 👏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-29 10:10 UTC, merged